name: gallery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  url_strategy:
  fluttertoast: ^8.2.2
  http: ^0.13.4
  another_flushbar: ^1.12.30
  provider: ^6.0.5
  shared_preferences:
  dartz:
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  pretty_logger:
  google_fonts:
  svg_flutter:
  skeletonizer:
  go_router:
  cached_network_image:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/
   - assets/images/

